version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - echo "AWS CLI version:"
      - aws --version

  pre_build:
    commands:
      - echo "Validating credentials..."
      - aws sts get-caller-identity
      - echo "Current region is $AWS_REGION"

  build:
    commands:
      - echo "Running analysis script..."
      - chmod +x ./script-analyze.sh
      - ./script-analyze.sh

  post_build:
    commands:
      - echo "Analysis complete!"
      - ls -la plan.txt

artifacts:
  files:
    - plan.txt
    - deploy.sh